name: Deploy Angular Project to GitHub

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      DEMO_APP_BASE_DIR: ./mk-magic-alerts-demo
      LIB_BASE_DIR: ./mk-magic-alerts-lib
      PROJECT_NAME: mk-magic-alerts
    steps:
      - name: Set TARGET_BRANCH variable
        run: echo "TARGET_BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Identify and set the latest 'v'-prefixed tag from the specified branch
        run: |
          # Fetch the specified branch
          git fetch --prune --unshallow -v origin ${{ env.TARGET_BRANCH }}
          
          # Fetch all tags
          git fetch --depth=1 -v origin +refs/tags/*:refs/tags/* --tags

          # Filter tags that start with 'v', sort them, and get the latest
          LATEST_DEPLOYED_VERSION=$(git tag -l "v*" | sort -V | tail -n1)
          LATEST_DEPLOYED_VERSION=${LATEST_DEPLOYED_VERSION#v} # Remove the 'v' prefix if needed
          echo "Latest Deployed Version: $LATEST_DEPLOYED_VERSION"
          echo "LATEST_DEPLOYED_VERSION=${LATEST_DEPLOYED_VERSION}" >> $GITHUB_ENV

      - name: Build and link mk-magic-alerts
        run: |
          (cd ${{ env.LIB_BASE_DIR }} && npm install && npm run build && npm link)
          (cd ${{ env.DEMO_APP_BASE_DIR }} && npm link ${{ env.PROJECT_NAME }})

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.DEMO_APP_BASE_DIR }}

      - name: Run Tests
        run: npm run test:ci
        working-directory: ${{ env.DEMO_APP_BASE_DIR }}

      - name: Check if Deployment is Needed
        id: version_check
        run: |
          # Extract the current version from package.json
          CURRENT_VERSION=$(node -p "require('${{ env.DEMO_APP_BASE_DIR }}/package.json').version")
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "Current Version: $CURRENT_VERSION"

          # Read the latest deployed version from the environment variable
          LATEST_DEPLOYED_VERSION=${{ env.LATEST_DEPLOYED_VERSION }}
          echo "Latest Deployed Version: $LATEST_DEPLOYED_VERSION"

          # Use sort to compare semantic versions, and consider deployment if the current is newer
          if [ "$(printf '%s\n' "$LATEST_DEPLOYED_VERSION" "$CURRENT_VERSION" | sort -V | head -n1)" != "$CURRENT_VERSION" ]; then
            echo "Version $CURRENT_VERSION is new. Proceeding with publish..."
            echo "deploy_needed=true" >> $GITHUB_ENV
          else
            echo "The current version is not newer; no deployment needed."
            echo "deploy_needed=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Angular Project
        if: env.deploy_needed == 'true'
        run: npm run deploy
        working-directory: ${{ env.DEMO_APP_BASE_DIR }}
        
      - name: Deploy to GitHub Pages
        if: env.deploy_needed == 'true'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: ${{ env.DEMO_APP_BASE_DIR }}/dist/${{ env.PROJECT_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '🚀 v${{ env.CURRENT_VERSION }} deployed to GitHub Pages'
      
      - name: Set a version-tag for the commit to the specified branch
        if: env.deploy_needed == 'true' && success()
        run: |
          # Set a tag preceding a 'v' on the specified branch
          git tag v${{ env.CURRENT_VERSION }}
          git push origin v${{ env.CURRENT_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
