name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

# Needed for OIDC (Trusted Publishing)
permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      BASE_DIR: ./mk-magic-alerts-lib
      PROJECT_NAME: mk-magic-alerts
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      # Checkout the repository to the runner
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      # Ensure a recent npm that supports Trusted Publishing + provenance
      - name: Ensure recent npm
        run: npm i -g npm@latest

      # Safety: remove any accidental project .npmrc that could force tokens
      - name: Remove local .npmrc if present
        run: rm -f .npmrc && rm -f $HOME/.npmrc

      # Install jq tool for JSON processing
      - name: Install jq
        run: sudo apt-get install -y jq

      # Install dependencies at the root level
      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ env.BASE_DIR }}
        env:
          NX_NATIVE: 'false'
          NX_DAEMON: 'false'

      # Run tests at the root level
      - name: Run Tests
        run: npm run test:ci
        working-directory: ${{ env.BASE_DIR }}

      # Report test coverage (for badge on npm-library-mainpage)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ env.CODECOV_TOKEN }}
          slug: mkeller1992/mk-magic-messages-library

      # Build the library from the specified subdirectory
      - name: Build Library
        run: npx ng build
        working-directory: ${{ env.BASE_DIR }}/projects/${{ env.PROJECT_NAME }}

      # Check if version has been updated
      - name: Check if version has been updated
        id: check_version
        run: |
          # Extract current and latest published version
          PACKAGE_NAME=$(jq -r '.name' package.json)
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

          # Public package: npm view works without auth
          LATEST_PUBLISHED_VERSION=$(npm view "$PACKAGE_NAME" version 2>/dev/null || echo "0.0.0")
          if [ "$CURRENT_VERSION" = "$LATEST_PUBLISHED_VERSION" ]; then
            echo "execute_publish=false" >> $GITHUB_ENV
          else
            echo "execute_publish=true" >> $GITHUB_ENV
          fi
        working-directory: ${{ env.BASE_DIR }}/dist/${{ env.PROJECT_NAME }}

      # Publish to npm via OIDC (no token)
      - name: Publish to npm via OIDC (no token)
        if: env.execute_publish == 'true'
        run: npm publish
        working-directory: ${{ env.BASE_DIR }}/dist/${{ env.PROJECT_NAME }}
        # No NODE_AUTH_TOKEN here — OIDC handles auth

      # Tag commit
      - name: Tag commit
        if: env.execute_publish == 'true' && success()
        run: |
          git tag v${{ env.CURRENT_VERSION }}-lib
          git push origin v${{ env.CURRENT_VERSION }}-lib
