name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the runner
    - uses: actions/checkout@v2

    # Install jq tool for JSON processing
    - name: Install jq
      run: sudo apt-get install jq

    # Setup Node.js environment
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 'lts/*' # Use the latest LTS version of Node.js
        registry-url: 'https://registry.npmjs.org'

    # Install dependencies at the root level
    - name: Install Dependencies
      run: npm install
      working-directory: ./mk-magic-alerts-lib

    # Run tests at the root level
    - name: Test
      run: npm run test:ci
      working-directory: ./mk-magic-alerts-lib

    # Build the library from the specified subdirectory
    - name: Build Library
      run: npm run build
      working-directory: ./mk-magic-alerts-lib/projects/mk-magic-alerts

    # Check if version has been updated
    - name: Check if version has been updated
      id: check_version
      run: |
        PACKAGE_NAME=$(jq -r '.name' package.json)
        CURRENT_VERSION=$(jq -r '.version' package.json)
        LATEST_PUBLISHED_VERSION=$(npm view $PACKAGE_NAME version 2>/dev/null || echo "0.0.0")
        if [ "$CURRENT_VERSION" = "$LATEST_PUBLISHED_VERSION" ]; then
          echo "Version $CURRENT_VERSION is already published. Skipping publish..."
          echo "::set-output name=skip_publish::true"
        else
          echo "Version $CURRENT_VERSION is new. Proceeding with publish..."
          echo "::set-output name=skip_publish::false"
        fi
      working-directory: ./mk-magic-alerts-lib/dist/mk-magic-alerts

    # Publish the library to npm if the version has been updated
    - name: Publish to npm
      if: steps.check_version.outputs.skip_publish == 'false'
      run: npm publish
      working-directory: ./mk-magic-alerts-lib/dist/mk-magic-alerts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_FOR_MAGIC_MSG_LIB }}